name: twist-2025-periodic-dna-self-stabilization
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # Basis-Abhängigkeiten aus dem Hauptprojekt
  - pip:
      - -r ../../requirements.txt
      # ggf. paper-spezifische Extras hier ergänzen
